import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navBar/NavBar.jsx";
import Footer from "@/components/footer/Footer.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen flex flex-col justify-between ">
          <NavBar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
